# Generated by Django 2.2.2 on 2019-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, help_text='Speak your mind: ', null=True),
        ),
    ]
